const axios = require('axios');

module.exports = {
    name: 'imagine',
    category: 'tools',
    description: 'Generate an image from a text prompt (free, no key)',
    async execute(sock, msg, args) {
        const from = msg.key.remoteJid;
        const prompt = args.join(' ');
        if (!prompt) {
            return await sock.sendMessage(from, { text: '❌ Usage: .imagine a cat wearing sunglasses' });
        }

        await sock.sendMessage(from, { text: `🎨 *Generating image for:*\n“${prompt}”\n_Please wait up to 15 seconds._` });

        try {
            const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=512&height=512&nologo=true`;
            await sock.sendMessage(from, {
                image: { url: imageUrl },
                caption: `🖼️ *Generated by AI*\nPrompt: ${prompt}\n\n╭━━━━━━━━━━━━━━━╮\n┃ 🔥 𝕾𝕬𝖁𝕬𝕲𝕰 𝕭𝖔𝖙 🔥\n╰━━━━━━━━━━━━━━━╯`
            });
        } catch (err) {
            console.error(err);
            await sock.sendMessage(from, { text: '❌ Image generation failed. Try a different prompt.' });
        }
    }
};
